### ISSUE TITLE
流式对话，如何终止chatgpt输出，问新的问题

### ISSUE THREAD

**Issue by mczha** [icecoins/ChatGPT_Android#5]

**Comment by icecoins** [comment]
这个问题我没有考虑过，下次更新或许会加一个终止按钮。最近毕设比较忙，更新暂时随缘

**Comment by mczha** [comment]
> 这个问题我没有考虑过，下次更新或许会加一个终止按钮。最近毕设比较忙，更新暂时随缘

终止的话，是有停止的指令吗？像官网的那个stop按钮？

**Comment by icecoins** [comment]
官方网页应该是直接调用模型的，stop之后模型就停止输出了。但是用api间接调用模型，我猜是没有停止指令的。
这要看官方在停止输出方面有什么建议，如果没有的话我应该会采用直接断开http连接达到终止输出的目的。
如果是直连，用断开连接来终止倒是简单。
但是用websocket中转的时候，是由中转服务器发起的连接，这种情况应该如何完全地终止一次对话，还是要时间考虑的。
